/* eslint-disable no-undef */
import axios from 'axios';

async function AbsoluteReality(data) {
  try {
    console.log('The image is generating by AbsoluteReality.');
    console.log(`Bearer ${import.meta.env.VITE_API_KEY}`);
    const response = await axios.post(
      'https://api-inference.huggingface.co/models/digiplay/AbsoluteReality_v1.8.1',
      data,
      {
        headers: {
          Authorization: `Bearer ${import.meta.env.VITE_API_KEY}`,
          'Content-Type': 'application/json'
        },
        responseType: 'blob'
      }
    );
    
    console.log('The image is generated by AbsoluteReality.');
    console.log(response.data);
    return response.data; 
  } catch (error) {
    console.error('Error in AbsoluteReality:', error);
  }
}

export default AbsoluteReality;
