import axios from 'axios';

async function AbsoluteReality(data) {
  try {
    console.log('The image is generating by AbsoluteReality.');
    const response = await axios.post(
      'https://api-inference.huggingface.co/models/digiplay/AbsoluteReality_v1.8.1',
      data,
      {
        headers: {
          Authorization: 'Bearer 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',
          'Content-Type': 'application/json'
        },
        responseType: 'blob' // Specify response type as Blob
      }
    );
    
    console.log('The image is generated by AbsoluteReality.');
    return response.data; // This will be a Blob object
  } catch (error) {
    console.error('Error in AbsoluteReality:', error);
    throw error; // Re-throw the error to handle it in the calling code
  }
}

export default AbsoluteReality;
