import axios from 'axios';

async function playground(data) {
  try {
    console.log('The image is generating by playgroundAI.');
    const response = await axios.post(
      'https://api-inference.huggingface.co/models/playgroundai/playground-v2-1024px-aesthetic',
      data,
      {
        headers: {
          Authorization: 'Bearer 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',
          'Content-Type': 'application/json'
        },
        responseType: 'blob' 
      }
    );

    // console.log("Response ----->>>>>    ",response);

    console.log('The image is generated by playgroundAI.');

    // console.log("Response.data ----->>>>>    ",response.data); 
    return response.data; // This will be a Blob object


  } catch (error) {
    console.error('Error in playground:', error);
    throw error; // Re-throw the error to handle it in the calling code
  }
}

export default playground;
