
async function runwayml(data) {
  console.log("The Image is Generating by runwayml.");
  const response = await fetch(
    "https://api-inference.huggingface.co/models/runwayml/stable-diffusion-v1-5",
    {
      headers: { Authorization: "Bearer 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" },
      method: "POST",
      body: JSON.stringify(data),
    }
  );
  const result = await response.blob();

  console.log("The Image is Generated by runwayml.");
  return result;
}


export default runwayml;
