import axios from 'axios';

async function stableDiffusion(data) {
  console.log("The Image is Generating by stable-diffusion.");

  try {
    const response = await axios.post(
      "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0",
      data,
      {
        headers: { Authorization: "Bearer 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" },
        responseType: 'blob',  // This ensures the response is handled as a Blob
      }
    );

    // console.log("Response ----->>>>>    ", response);

    const result = response.data;

    // console.log("Result ----->>>>>    ", result);
	console.log("The Image is Generated by stableDiffusion.");

    return result;
  } catch (error) {
    console.error("Error generating image:", error);
    throw error;  // Ensure the error is propagated if needed
  }
}

export default stableDiffusion;
